apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-agent
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  annotations:
    codefresh.io/product: kubeagent
spec:
  project: default
  destination:
    name: in-cluster
  source:
    repoURL: https://github.com/OctopusDeploy/helm-charts.git
    targetRevision: ''
    chart: kubernetes-agent
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
