apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-agent
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  annotations:
    codefresh.io/product: kubeagent
spec:
  project: default
  destination:
    name: in-cluster
    namespace: default
  source:
    repoURL: https://ghcr.io/octopusdeploy/octopusdeploy-helm
    targetRevision: 1.6.0
    chart: octopusdeploy-helm
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
