apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-agent
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  annotations:
    codefresh.io/product: helloworld
spec:
  project: default
  destination:
    name: in-cluster
    namespace: default
  source:
    repoURL: https://finniandempsey.github.io/helm-repo/index.yaml
    targetRevision: 0.1.1
    chart: helm-custom-html
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
