apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-helm
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  annotations:
    codefresh.io/product: helloworld
spec:
  project: default
  destination:
    name: in-cluster
    namespace: staging
  source:
    path: manifests/helloworld-staging
    repoURL: https://github.com/FinnianDempsey/gitops-helloworld.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
