apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-helm
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  annotations:
    codefresh.io/product: helloworld
spec:
  project: default
  destination:
    name: in-cluster
    namespace: cf-kubeagent
  source:
    repoURL: oci://registry-1.docker.io/octopusdeploy/kubernetes-agent
    targetRevision: 2.19.1
    chart: kubernetes-agent
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
